version: '2'

services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - discovery.type=single-node
    volumes:
      - dados-elastic-search:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  dados-elastic-search:
    external: true
